# Fish completions for aicommit
# Generated by aicommit --fish-completions

# Complete flags
complete -c aicommit -s a -l add-all -d 'Stage all changes'
complete -c aicommit -s P -l provider -x -a 'claude openrouter aichat' -d 'LLM provider'
complete -c aicommit -s m -l model -x -d 'Model name (provider-specific)'
complete -c aicommit -s t -l test -d 'Run unit and regression tests'
complete -c aicommit -s h -l help -d 'Show help message'
complete -c aicommit -s v -l version -d 'Show version information'
complete -c aicommit -l fish-completions -d 'Install fish shell completions'

