# Fish completions for bullets
# Generated by bullets --fish-completions

complete -c bullets -s h -l help -d 'Show help message'
complete -c bullets -s v -l version -d 'Show version information'
complete -c bullets -l test -d 'Run unit and regression tests'
complete -c bullets -l fish-completions -d 'Install fish shell completions'
complete -c bullets -s o -l output -d 'Output file (default: stdout)' -r
complete -c bullets -s a -l append -d 'Append to output file'
complete -c bullets -s p -l prompt -d 'Custom prompt file' -r
complete -c bullets -l format -d 'Output format (bullets, numbered, outline)' -r

# Complete with document file names
complete -c bullets -f -a '(__fish_complete_suffix .txt)'
complete -c bullets -f -a '(__fish_complete_suffix .md)'

