# Fish completions for clean-transcript
# Generated by clean-transcript --fish-completions

complete -c clean-transcript -s h -l help -d 'Show help message'
complete -c clean-transcript -s v -l version -d 'Show version information'
complete -c clean-transcript -l test -d 'Run unit and regression tests'
complete -c clean-transcript -l fish-completions -d 'Install fish shell completions'
complete -c clean-transcript -s o -l output -d 'Output file path (default: <input>.clean.md)' -r
complete -c clean-transcript -s f -l force -d 'Overwrite existing output file'

# Complete with transcript file names
complete -c clean-transcript -f -a '(__fish_complete_suffix .txt)'
complete -c clean-transcript -f -a '(__fish_complete_suffix .vtt)'
complete -c clean-transcript -f -a '(__fish_complete_suffix .srt)'

