# Fish completions for ncsu-vpn
# Generated by ncsu-vpn --fish-completions

complete -c ncsu-vpn -f

# Subcommands
complete -c ncsu-vpn -n '__fish_use_subcommand' -a connect -d 'Bring up the VPN tunnel'
complete -c ncsu-vpn -n '__fish_use_subcommand' -a disconnect -d 'Tear down the VPN tunnel'
complete -c ncsu-vpn -n '__fish_use_subcommand' -a status -d 'Show tunnel state, routes and DNS'

# Flags
complete -c ncsu-vpn -s h -l help -d 'Show help message'
complete -c ncsu-vpn -s v -l version -d 'Show version information'
complete -c ncsu-vpn -s u -l user -d 'Unity ID to authenticate as' -x
complete -c ncsu-vpn -s g -l group -d 'Gateway auth group' -x -a '1-Faculty-and-Staff 2-Student 3-Student-Health-Center 4-Vendor 5-OIT-Staff 6-Faculty-and-Staff-FT 7-Student-FT 8-Workshop-Temp'
complete -c ncsu-vpn -l full -d 'Use the full-tunnel group (6-Faculty-and-Staff-FT)'
complete -c ncsu-vpn -s d -l duo -d 'Duo second factor' -x -a 'push sms phone'
complete -c ncsu-vpn -s f -l foreground -d 'Stay in foreground (Ctrl-C disconnects)'
complete -c ncsu-vpn -l test -d 'Run unit and regression tests'
complete -c ncsu-vpn -l fish-completions -d 'Install fish shell completions'
