# Fish completions for pdf2pdfa
# Generated by pdf2pdfa --fish-completions

# Complete flags
complete -c pdf2pdfa -s h -l help -d 'Show help message'
complete -c pdf2pdfa -s v -l version -d 'Show version information'
complete -c pdf2pdfa -l test -d 'Run unit and regression tests'
complete -c pdf2pdfa -l fish-completions -d 'Install fish shell completions'
complete -c pdf2pdfa -s o -l output -d 'Specify output file path' -r

# Complete PDF files as arguments
complete -c pdf2pdfa -f -a '*.pdf' -d 'PDF file'
