# Fish completions for scratch
# Generated by scratch --fish-completions

# Complete flags
complete -c scratch -s h -l help -d 'Show help message'
complete -c scratch -s v -l version -d 'Show version information'
complete -c scratch -s c -l cat -d 'Print file contents to stdout'
complete -c scratch -l test -d 'Run unit and regression tests'
complete -c scratch -l fish-completions -d 'Install fish shell completions'
complete -c scratch -l iso -d 'Create file with ISO 8601 timestamp'

# Complete with existing scratch files
complete -c scratch -f -a '(test -d ~/.scratch && begin; find ~/.scratch -name "*.md" -type f -exec stat -f "%m %N" {} \; | sort -rn | cut -d" " -f2- | xargs -n1 basename | string replace .md ""; end)'

