# Fish completions for transcribe
# Generated by transcribe --fish-completions

# Complete flags
complete -c transcribe -s h -l help -d 'Show help message'
complete -c transcribe -s v -l version -d 'Show version information'
complete -c transcribe -l test -d 'Run unit and regression tests'
complete -c transcribe -l fish-completions -d 'Install fish shell completions'
complete -c transcribe -l save -d 'Save transcription to file (default: stdout)'

# Whisper-specific options that can be passed through
complete -c transcribe -l model -d 'Whisper model to use' -xa 'tiny base small medium large'
complete -c transcribe -l language -d 'Language spoken in the audio'
complete -c transcribe -l task -d 'Task to perform' -xa 'transcribe translate'
complete -c transcribe -l output_format -d 'Output format' -xa 'txt vtt srt json'
complete -c transcribe -l output_dir -d 'Directory to save output files'
complete -c transcribe -l device -d 'Device to use for inference' -xa 'cpu cuda'

# File completion for audio files
complete -c transcribe -f -a '(__fish_complete_suffix .mp3 .wav .m4a .ogg .flac .mp4 .avi .mkv .mov)'

