# Fish completions for yt-mp3
# Generated by yt-mp3 --fish-completions

# Complete flags
complete -c yt-mp3 -s h -l help -d 'Show help message'
complete -c yt-mp3 -s v -l version -d 'Show version information'
complete -c yt-mp3 -s q -l quiet -d 'Suppress progress output'
complete -c yt-mp3 -l verbose -d 'Show detailed yt-dlp output'
complete -c yt-mp3 -l test -d 'Run unit and regression tests'
complete -c yt-mp3 -l fish-completions -d 'Install fish shell completions'

